apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  type: NodePort
  selector:
    app: mosquitto
  ports:
  - port: {{ .Values.mosquitto.port }}
    nodePort: {{ .Values.mosquitto.nodePort }}
    protocol: TCP

