apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongo.deployment.name }}
  labels:
    name: {{ .Values.mongo.label.name }}
spec:
  replicas: 1
  selector:
    matchLabels: 
      name: {{ .Values.mongo.label.name }}
  strategy:
    type: RollingUpdate 
  template:
    metadata:
      name: mongo-db
      labels:
        name: {{ .Values.mongo.label.name }}
    spec:
      {{- if .Values.mongo.volume.selectNode }}
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.mongo.volume.node }}
      {{- end }}
      containers:
        - name: mongo-db
          image: {{ .Values.mongo.image }}
          imagePullPolicy: IfNotPresent
          args: ["--nojournal"]
          volumeMounts:
            - name: {{ .Values.mongo.volume.name }}
              mountPath: {{ .Values.mongo.volume.mountPath }}
      volumes:
{{- if .Values.mongo.persistence.enabled }}
        - name: {{ .Values.mongo.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.mongo.volume.name }}
{{- else }}
        - name: {{ .Values.mongo.volume.name }}
          {{- if .Values.mongo.volume.isHostPath }}
          hostPath:
            path: {{ .Values.mongo.volume.hostPath }}
          {{- else if .Values.mongo.volume.isVolumeClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.mongo.volume.claimName }}
          {{- else }}
          emptyDir: {}
          {{- end}}
{{- end }}

{{- if .Values.mongo.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mongo.volume.name }}
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "{{ .Values.mongo.persistence.storage }}"
  storageClassName: {{ .Values.mongo.persistence.storageClassName }}
{{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.service.name }}
  labels:
    name: {{ .Values.mongo.label.name }}
spec:
  type: ClusterIP
  selector:
    name: {{ .Values.mongo.label.name }}
  ports:
    - name: mongodb
      port: {{ .Values.mongo.dbport }}
      protocol: TCP
