{{- if .Values.aei_contract.deploy }}
apiVersion: v1
kind:  Pod
metadata:
  name: {{ .Values.aei_contract.label.name }}
spec:
  containers:
  - name: {{ .Values.aei_contract.service.name }}
    image: {{ .Values.aei_contract.image }}
    env:
    - name: KRT_VAR
      value: "hello krt"
    - name: RPC_ENDPOINT
      value: "{{ .Values.aei_contract.env.RPC_ENDPOINT }}"
    - name: RPC_PORT
      value: "{{ .Values.aei_contract.env.RPC_PORT }}"
    volumeMounts:
      - mountPath: /.config
        name: config-volume
  volumes:
    - name: config-volume
      emptyDir: {}
  restartPolicy: OnFailure
{{- end }}
