{{ if .Values.canis_major.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.canis_major.label.name }}
  labels:
    name: {{ .Values.canis_major.label.name }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.canis_major.label.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.canis_major.label.name }}
    spec:
      containers:
      - name: {{ .Values.canis_major.service.name }}
        image: {{ .Values.canis_major.image }}
        env:
        - name: MICRONAUT_SERVER_PORT
          value: "{{ .Values.canis_major.env.MICRONAUT_SERVER_PORT }}"
        - name: MICRONAUT_HTTP_SERVICES_NGSI_URL
          value: {{ .Values.canis_major.env.MICRONAUT_HTTP_SERVICES_NGSI_URL }}
        - name: MICRONAUT_HTTP_SERVICES_NGSI_PATH
          value: {{ .Values.canis_major.env.MICRONAUT_HTTP_SERVICES_NGSI_PATH }}
        - name: ETHEREUM_CONTRACT_ADDRESS
          value: {{ .Values.canis_major.env.ETHEREUM_CONTRACT_ADDRESS }}
        - name: ETHEREUM_DLT_ADDRESS
          value: {{ .Values.canis_major.env.ETHEREUM_DLT_ADDRESS }}
        - name: GENERAL_NGSI_TENANT
          value: {{ .Values.canis_major.env.GENERAL_NGSI_TENANT }}  
        - name: DEFAULT_ACCOUNT_ENABLED
          value: "{{ .Values.canis_major.env.DEFAULT_ACCOUNT_ENABLED }}"
        - name: DEFAULT_ACCOUNT_PRIVATE_KEY
          value: {{ .Values.canis_major.env.DEFAULT_ACCOUNT_PRIVATE_KEY }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.canis_major.service.name }}
  labels:
    name: {{ .Values.canis_major.label.name }}
spec:
  type: ClusterIP
  selector:
      name: {{ .Values.canis_major.label.name }}
  ports:
  - port: {{ .Values.canis_major.port }}
    protocol: TCP
    name: {{ .Values.canis_major.portName }}
{{- end }}
