---
# Source: trust-anchor/charts/mysql/templates/primary/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: trust-anchor-mysql
data:
  mysqld.cnf: |-
    [mysqld]
    default_authentication_plugin=mysql_native_password
    skip-name-resolve
    explicit_defaults_for_timestamp
    port=3306
    max_allowed_packet=16M
    bind-address=*
    character-set-server=UTF8
    collation-server=utf8_general_ci
    slow_query_log=0
    long_query_time=10.0

    skip-log-bin

    [client]
    port=3306
    default-character-set=UTF8
    
    [manager]
    port=3306



