apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: {{ .Values.mysql.image }}
        imagePullPolicy: "IfNotPresent"
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-database-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-database-secret
              key: mysql-password
        - name: MYSQL_USER
          value: tirdb
        - name: MYSQL_PASSWORD
          value: tirdb
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: {{ .Values.mysql.volume.name }}
          mountPath: /var/lib/mysql
        - name: config
          mountPath: /etc/mysql/conf.d/mysqld.cnf
          subPath: mysqld.cnf
      volumes:
        - name: {{ .Values.mysql.volume.name }}
          {{- if .Values.mysql.volume.isHostPath }}
          hostPath:
            path: {{ .Values.mysql.volume.hostPath }}
          {{- else if .Values.mysql.volume.isVolumeClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.mysql.volume.claimName }}
          {{- else }}
          emptyDir: {}
          {{- end}}
        - name: config
          configMap:
            name: trust-anchor-mysql
  


---

apiVersion: v1
kind: Service
metadata:
  name: trust-anchor-mysql
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 3306
    name: mysql
    targetPort: mysql
  selector:
    app: mysql
