{{- if .Values.mintaka.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mintaka
  labels:
    name: mintaka
spec:
  replicas: 1
  selector:
    matchLabels: 
      name: mintaka
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: mintaka
      labels:
        name: mintaka
    spec:
      restartPolicy: Always
      containers:
        - name: timescale
          image: {{ .Values.mintaka.image }}
          ports:
          - containerPort: {{ .Values.mintaka.port }}
          env:
          - name: DATASOURCES_DEFAULT_HOST
            value: timescale
          - name: DATASOURCES_DEFAULT_USERNAME
            value: {{ .Values.mintaka.timescale.username }}
          - name: DATASOURCES_DEFAULT_PASSWORD
            value: {{ .Values.mintaka.timescale.password }}
          - name: DATASOURCES_DEFAULT_DATABASE
            value: orion
          - name: MICRONAUT_SERVER_HOST
            value: "0.0.0.0"
          - name: MICRONAUT_SERVER_PORT
            value: "8080"
          - name: JAVA_OPTS
            value: "-Djava.net.preferIPv4Stack=true"

---
apiVersion: v1
kind: Service
metadata:
  name: mintaka
  labels:
    app: mintaka
spec:
  type: ClusterIP
  selector:
    name: mintaka
  ports:
  - port: {{ .Values.mintaka.port }}
    protocol: TCP
    name: mintaka-port
{{- end }}

---
{{- if .Values.mintaka.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mintaka
spec:
  rules:
  - host: {{ .Values.mintaka.service.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mintaka
            port: 
              number: 8080
{{- end }}
