canis_major:
  enabled: true
  label:
    name: canis-major
  deploy_cm_forward_proxy: True
  image: quay.io/fiware/canis-major
  service:
    name: canis-major
  port: 4000
  nodePort: 31400
  env:
    MICRONAUT_SERVER_PORT: "4000"
    MICRONAUT_HTTP_SERVICES_NGSI_URL: "http://orion-ld-service.orion.svc.cluster.local"
    MICRONAUT_HTTP_SERVICES_NGSI_PATH: ngsi-ld/v1
    # Ununderstandable
    ETHEREUM_CONTRACT_ADDRESS: 0x476059cd57800db8eb88f67c2aa38a6fcf8251e0
    ETHEREUM_DLT_ADDRESS: ganache-cli:8545
    GENERAL_NGSI_TENANT: orion
    DEFAULT_ACCOUNT_ENABLED: true
    # default key derived from the mnemonic in the test definition
    DEFAULT_ACCOUNT_PRIVATE_KEY: 0x82AC43A26ae509eEf217330C7d862F822fF0CECB
  ingress:
    enabled: true
    host: canis-major.apps-crc.testing
