{{- if .Values.orion.troe }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mintaka
  labels:
    name: mintaka
spec:
  replicas: 1
  selector:
    matchLabels: 
      name: mintaka
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: mintaka
      labels:
        name: mintaka
    spec:
      restartPolicy: Always
      containers:
        - name: timescale
          image: {{ .Values.mintaka.image }}
          env:
          - name: DATASOURCES_DEFAULT_HOST
            value: timescale
          - name: DATASOURCES_DEFAULT_USERNAME
            value: {{ .Values.timescale.username }}
          - name: DATASOURCES_DEFAULT_PASSWORD
            value: {{ .Values.timescale.password }}
          - name: DATASOURCES_DEFAULT_DATABASE
            value: orion
          ports:
            - containerPort: {{ .Values.mintaka.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: mintaka
  labels:
    app: mintaka
spec:
  type: NodePort
  selector:
    app: mintaka
  ports:
  - port: {{ .Values.mintaka.port }}
    nodePort: {{ .Values.mintaka.nodePort }}
    protocol: TCP
    name: mintaka-port
{{- end }}
