apiVersion: apps/v1
kind: Deployment
metadata:
  name: orion-ld
  labels:
    name: {{ .Values.orionld.label.name }}
spec:
  replicas: 1
  selector:
    matchLabels: 
      name: {{ .Values.orionld.label.name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: orion-ld
      labels:
        name: {{ .Values.orionld.label.name }}
    spec:
      restartPolicy: Always
      containers:
        - name: orion-ld
          image: {{ .Values.orionld.image }}
          imagePullPolicy: Always
          {{- if .Values.orionld.troe }}
          env:
          - name: ORIONLD_TROE
            value: "TRUE"
          - name: ORIONLD_TROE_USER
            value: {{ .Values.orionld.timescale.username }}
          - name: ORIONLD_TROE_PWD
            value: {{ .Values.orionld.timescale.password }}
          - name: ORIONLD_TROE_HOST
            value: {{ .Values.orionld.timescale.host }}
          {{- end}}
          args: 
            - -dbhost
            - {{ .Values.orionld.mongodb.host }}
            - -logLevel
            - {{ .Values.orionld.loglevel }}
            {{- if .Values.orionld.mongoconly }}
            - -mongocOnly
            {{- end }}
            {{- if .Values.orionld.experimental }}
            - -experimental
            {{- end }}
            {{- if .Values.orionld.forwarding }}
            - -forwarding
            - -wip
            - entityMaps
            {{- end }}
            {{- if .Values.orionld.troe }}
            - -troe
            {{- end }}
            - -port
            - "{{ .Values.orionld.port }}"
          ports:
            - containerPort: {{ .Values.orionld.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.orionld.service.name }}
  labels:
    name: {{ .Values.orionld.label.name }}
spec:
  type: ClusterIP
  selector:
    name: {{ .Values.orionld.label.name }}
  ports:
    - name: ngsild
      port: {{ .Values.orionld.exposedPort }}
      targetPort: {{ .Values.orionld.port }}
      protocol: TCP

