apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgres.sel_name }}
  labels:
    name: {{ .Values.postgres.sel_name }}
spec:
  selector:
    matchLabels: 
      name: {{ .Values.postgres.sel_name }}
  template:
    metadata:
      labels:
        name: {{ .Values.postgres.sel_name }}
    spec:
      containers:
        - image: {{ .Values.postgres.image }}
          imagePullPolicy: "IfNotPresent"
          name: {{ .Values.postgres.sel_name }}
          env:
          - name: POSTGRES_PASSWORD
            value: orion
          volumeMounts:
            - name: {{ .Values.postgres.volume.name }}
              mountPath: {{ .Values.postgres.volume.mountPath }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
      volumes:
{{- if .Values.postgres.persistence.enabled }}
        - name: {{ .Values.postgres.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.postgres.volume.name }}
{{- else }}
        - name: {{ .Values.postgres.volume.name }}
          {{- if .Values.postgres.volume.isHostPath }}
          hostPath:
            path: {{ .Values.postgres.volume.hostPath }}
          {{- else if .Values.postgres.volume.isVolumeClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.postgres.volume.claimName }}
          {{- else }}
          emptyDir: {}
          {{- end}}
{{- end }}

{{- if .Values.postgres.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgres.volume.name }}
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "{{ .Values.postgres.persistence.storage }}"
  storageClassName: {{ .Values.postgres.persistence.storageClassName }}
{{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.service_name }}
  labels:
    name: {{ .Values.postgres.sel_name }}
spec:
  type: ClusterIP
  selector:
    name: {{ .Values.postgres.sel_name }}
  ports:
    - name: postgres
      port: {{ .Values.postgres.port }}
      protocol: TCP
