orionld:
  experimental: true
  port: 1026
  exposedPort: 1026
  image: quay.io/fiware/orion-ld
  label:
    name: orion-ld-rs
  service:
    name: orion-ld-service
    hostname: orion.k8s.fiware.org
  loglevel: DEBUG
  troe: false
  ingress:
    enabled: true
    host: k8s.fiware.org
  mongodb:
    enabled: true
    host: mongodb

## May it define value.timescale.xxxx
