{{- if .Values.ganache_cli.aei_contract.enabled }}
apiVersion: v1
kind:  Pod
metadata:
  name: {{ .Values.ganache_cli.aei_contract.label.name }}
spec:
  containers:
  - name: {{ .Values.ganache_cli.aei_contract.service.name }}
    image: {{ .Values.ganache_cli.aei_contract.image }}
    env:
    - name: RPC_ENDPOINT
      value: "{{ .Values.ganache_cli.service.name }}"
    - name: RPC_PORT
      {{ if .Values.ganache_cli.sidecar.enabled }}
      value: "{{ .Values.ganache_cli.sidecar.port }}"
      {{ else }}
      value: "{{ .Values.ganache_cli.port }}"
      {{- end }}

    volumeMounts:
      - mountPath: /.config
        name: config-volume
  volumes:
    - name: config-volume
      emptyDir: {}
  restartPolicy: OnFailure
{{- end }}
