apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.iotagent_json.metadata.name }}
  labels:
    name: {{ .Values.iotagent_json.label.name }}
spec:
  type: NodePort
  selector:
    name: {{ .Values.iotagent_json.label.name }}
  ports:
  - port: {{ .Values.iotagent_json.iota_config_port }}
    nodePort: {{ .Values.iotagent_json.iota_config_node_port }}
    protocol: TCP
    name: iota-config-port
  - port: {{ .Values.iotagent_json.iota_httpport }}
    nodePort: {{ .Values.iotagent_json.iota_node_httpport }}
    protocol: TCP
    name: iota-httpport

---
{{- if .Values.iotagent_json.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.iotagent_json.metadata.name }}
spec:
  rules:
  - host: {{ .Values.iotagent_json.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.iotagent_json.service.name }}
            port:
              number: 7896
{{- end }}
