mintaka:
  enabled: true
  port: 8080
  nodePort: 30880
  installMintaka: false
  dasource_host: timescale
  datasource_username: orion
  datasource_password: orion
  image: quay.io/fiware/mintaka:latest
  label:
    name: mintaka
  service:
    name: mintaka
  ingress:
    enabled: true
    host: mintaka.k8s.fiware.org
  timescale:
    service_name: timescale
    username: orion
    password: orion
